"""add_grupos_pago

Revision ID: c52b67fe0c8c
Revises: 3eb7fcfb6ea4
Create Date: 2026-06-25 04:55:14.416802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c52b67fe0c8c'
down_revision: Union[str, None] = '3eb7fcfb6ea4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grupos_pago',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grupos_pago_id'), 'grupos_pago', ['id'], unique=False)
    op.add_column('items', sa.Column('grupo_pago_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'items', 'grupos_pago', ['grupo_pago_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'items', type_='foreignkey')
    op.drop_column('items', 'grupo_pago_id')
    op.drop_index(op.f('ix_grupos_pago_id'), table_name='grupos_pago')
    op.drop_table('grupos_pago')
    # ### end Alembic commands ###
