"""add_productos_and_refactor_items

Revision ID: fe0a91eb3374
Revises: c52b67fe0c8c
Create Date: 2026-07-20 17:58:47.586716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe0a91eb3374'
down_revision: Union[str, None] = 'c52b67fe0c8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('productos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('precio', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('categoria', sa.Enum('bebidas', 'comidas', 'postres', 'otros', name='categoriaproducto'), nullable=False),
    sa.Column('disponible', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_productos_id'), 'productos', ['id'], unique=False)
    op.add_column('items', sa.Column('producto_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'items', 'productos', ['producto_id'], ['id'])
    op.drop_column('items', 'comensal')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('comensal', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'items', type_='foreignkey')
    op.drop_column('items', 'producto_id')
    op.drop_index(op.f('ix_productos_id'), table_name='productos')
    op.drop_table('productos')
    # ### end Alembic commands ###
